name: AVC
title: AVC
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable : true

highlighter: rouge
  
rouge:
  style: base16.monokai

theme: minima

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
